set nocompatible
set ignorecase
set smartcase
set incsearch
set hlsearch
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set autoindent
set backspace=indent,eol,start
set wrapscan
set noshowmatch
set wildmenu
set formatoptions+=mM
set title
set number
set ruler
set nolist
set listchars=tab:>-,extends:<,trail:-,eol:<
set wrap
set laststatus=2
set showcmd
set showmode
set nobackup
set noswapfile
set noerrorbells
filetype indent on
syntax on
filetype on
nnoremap <ESC><ESC> :nohlsearch<CR>
set ttimeout
set ttimeoutlen=50
set clipboard=unnamedplus
colorscheme pablo
